<?php

namespace Database\Seeders;

use App\Models\Ciudad;
use Illuminate\Database\Seeder;

class CiudadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = array(
            ['nombre' => "EL ENCANTO",   'departamento_id' =>  1],
            ['nombre' => "LA CHORRERA", 'departamento_id' =>  1],
            ['nombre' => "LA PEDRERA", 'departamento_id' =>  1],
            ['nombre' => "LA VICTORIA", 'departamento_id' =>  1],
            ['nombre' => "LETICIA", 'departamento_id' =>  1],
            ['nombre' => "MIRITÍ - PARANÁ", 'departamento_id' =>  1],
            ['nombre' => "PUERTO ALEGRIA", 'departamento_id' =>  1],
            ['nombre' => "PUERTO ARICA", 'departamento_id' =>  1],
            ['nombre' => "PUERTO NARIÑO", 'departamento_id' =>  1],
            ['nombre' => "PUERTO SANTANDER", 'departamento_id' => 1],
            ['nombre' => "TARAPACÁ", 'departamento_id' => 1],
            ['nombre' => "ABEJORRAL", 'departamento_id' => 2],
            ['nombre' => "ABRIAQUI", 'departamento_id' => 2],
            ['nombre' => "ALEJANDRIA", 'departamento_id' => 2],
            ['nombre' => "AMAGA", 'departamento_id' => 2],
            ['nombre' => "AMALFI", 'departamento_id' => 2],
            ['nombre' => "ANDES", 'departamento_id' => 2],
            ['nombre' => "ANGELOPOLIS", 'departamento_id' => 2],
            ['nombre' => "ANGOSTURA", 'departamento_id' => 2],
            ['nombre' => "ANORI", 'departamento_id' => 2],
            ['nombre' => "ANZA", 'departamento_id' => 2],
            ['nombre' => "APARTADO", 'departamento_id' => 2],
            ['nombre' => "ARBOLETES", 'departamento_id' => 2],
            ['nombre' => "ARGELIA", 'departamento_id' => 2],
            ['nombre' => "ARMENIA", 'departamento_id' => 2],
            ['nombre' => "BARBOSA", 'departamento_id' => 2],
            ['nombre' => "BELLO", 'departamento_id' => 2],
            ['nombre' => "BELMIRA", 'departamento_id' => 2],
            ['nombre' => "BETANIA", 'departamento_id' => 2],
            ['nombre' => "BETULIA", 'departamento_id' => 2],
            ['nombre' => "BRICEÑO", 'departamento_id' => 2],
            ['nombre' => "BURITICA", 'departamento_id' => 2],
            ['nombre' => "CACERES", 'departamento_id' => 2],
            ['nombre' => "CAICEDO", 'departamento_id' => 2],
            ['nombre' => "CALDAS", 'departamento_id' => 2],
            ['nombre' => "CAMPAMENTO", 'departamento_id' => 2],
            ['nombre' => "CAÑASGORDAS", 'departamento_id' => 2],
            ['nombre' => "CARACOLI", 'departamento_id' => 2],
            ['nombre' => "CARAMANTA", 'departamento_id' => 2],
            ['nombre' => "CAREPA", 'departamento_id' => 2],
            ['nombre' => "CAROLINA", 'departamento_id' => 2],
            ['nombre' => "CAUCASIA", 'departamento_id' => 2],
            ['nombre' => "CHIGORODO", 'departamento_id' => 2],
            ['nombre' => "CISNEROS", 'departamento_id' => 2],
            ['nombre' => "CIUDAD BOLÍVAR", 'departamento_id' => 2],
            ['nombre' => "COCORNA", 'departamento_id' => 2],
            ['nombre' => "CONCEPCION", 'departamento_id' => 2],
            ['nombre' => "CONCORDIA", 'departamento_id' => 2],
            ['nombre' => "COPACABANA", 'departamento_id' => 2],
            ['nombre' => "DABEIBA", 'departamento_id' => 2],
            ['nombre' => "DONMATIAS", 'departamento_id' => 2],
            ['nombre' => "EBEJICO", 'departamento_id' => 2],
            ['nombre' => "EL BAGRE", 'departamento_id' => 2],
            ['nombre' => "EL CARMEN DE VIBORAL", 'departamento_id' => 2],
            ['nombre' => "EL SANTUARIO", 'departamento_id' => 2],
            ['nombre' => "ENTRERRIOS", 'departamento_id' => 2],
            ['nombre' => "ENVIGADO", 'departamento_id' => 2],
            ['nombre' => "FREDONIA", 'departamento_id' => 2],
            ['nombre' => "FRONTINO", 'departamento_id' => 2],
            ['nombre' => "GIRALDO", 'departamento_id' => 2],
            ['nombre' => "GIRARDOTA", 'departamento_id' => 2],
            ['nombre' => "GOMEZ PLATA", 'departamento_id' => 2],
            ['nombre' => "GRANADA", 'departamento_id' => 2],
            ['nombre' => "GUADALUPE", 'departamento_id' => 2],
            ['nombre' => "GUARNE", 'departamento_id' => 2],
            ['nombre' => "GUATAPE", 'departamento_id' => 2],
            ['nombre' => "HELICONIA", 'departamento_id' => 2],
            ['nombre' => "HISPANIA", 'departamento_id' => 2],
            ['nombre' => "ITAGUI", 'departamento_id' => 2],
            ['nombre' => "ITUANGO", 'departamento_id' => 2],
            ['nombre' => "JARDIN", 'departamento_id' => 2],
            ['nombre' => "JERICO", 'departamento_id' => 2],
            ['nombre' => "LA CEJA", 'departamento_id' => 2],
            ['nombre' => "LA ESTRELLA", 'departamento_id' => 2],
            ['nombre' => "LA PINTADA", 'departamento_id' => 2],
            ['nombre' => "LA UNION", 'departamento_id' => 2],
            ['nombre' => "LIBORINA", 'departamento_id' => 2],
            ['nombre' => "MACEO", 'departamento_id' => 2],
            ['nombre' => "MARINILLA", 'departamento_id' => 2],
            ['nombre' => "MEDELLIN", 'departamento_id' => 2],
            ['nombre' => "MONTEBELLO", 'departamento_id' => 2],
            ['nombre' => "MURINDO", 'departamento_id' => 2],
            ['nombre' => "MUTATA", 'departamento_id' => 2],
            ['nombre' => "NARIÑO", 'departamento_id' => 2],
            ['nombre' => "NECHI", 'departamento_id' => 2],
            ['nombre' => "NECOCLI", 'departamento_id' => 2],
            ['nombre' => "OLAYA", 'departamento_id' => 2],
            ['nombre' => "PEÑOL", 'departamento_id' => 2],
            ['nombre' => "PEQUE", 'departamento_id' => 2],
            ['nombre' => "PUEBLORRICO", 'departamento_id' => 2],
            ['nombre' => "PUERTO BERRIO", 'departamento_id' => 2],
            ['nombre' => "PUERTO NARE", 'departamento_id' => 2],
            ['nombre' => "PUERTO TRIUNFO", 'departamento_id' => 2],
            ['nombre' => "REMEDIOS", 'departamento_id' => 2],
            ['nombre' => "RETIRO", 'departamento_id' => 2],
            ['nombre' => "RIONEGRO", 'departamento_id' => 2],
            ['nombre' => "SABANALARGA", 'departamento_id' => 2],
            ['nombre' => "SABANETA", 'departamento_id' => 2],
            ['nombre' => "SALGAR", 'departamento_id' => 2],
            ['nombre' => "SAN ANDRES", 'departamento_id' =>  2],
            ['nombre' => "SAN CARLOS", 'departamento_id' => 2],
            ['nombre' => "SAN FRANCISCO", 'departamento_id' => 2],
            ['nombre' => "SAN JERONIMO", 'departamento_id' => 2],
            ['nombre' => "SAN JOSE DE LA MONTAÑA", 'departamento_id' => 2],
            ['nombre' => "SAN JUAN DE URABA", 'departamento_id' => 2],
            ['nombre' => "SAN LUIS", 'departamento_id' => 2],
            ['nombre' => "SAN PEDRO", 'departamento_id' => 2],
            ['nombre' => "SAN PEDRO DE URABA", 'departamento_id' => 2],
            ['nombre' => "SAN RAFAEL", 'departamento_id' => 2],
            ['nombre' => "SAN ROQUE", 'departamento_id' => 2],
            ['nombre' => "SAN VICENTE", 'departamento_id' => 2],
            ['nombre' => "SANTA BARBARA", 'departamento_id' => 2],
            ['nombre' => "SANTA ROSA DE OSOS", 'departamento_id' => 2],
            ['nombre' => "SANTAFÉ DE ANTIOQUIA", 'departamento_id' => 2],
            ['nombre' => "SANTO DOMINGO", 'departamento_id' => 2],
            ['nombre' => "SEGOVIA", 'departamento_id' => 2],
            ['nombre' => "SONSON", 'departamento_id' => 2],
            ['nombre' => "SOPETRAN", 'departamento_id' => 2],
            ['nombre' => "TAMESIS", 'departamento_id' => 2],
            ['nombre' => "TARAZA", 'departamento_id' => 2],
            ['nombre' => "TARSO", 'departamento_id' => 2],
            ['nombre' => "TITIRIBI", 'departamento_id' => 2],
            ['nombre' => "TOLEDO", 'departamento_id' => 2],
            ['nombre' => "TURBO", 'departamento_id' => 2],
            ['nombre' => "URAMITA", 'departamento_id' => 2],
            ['nombre' => "URRAO", 'departamento_id' => 2],
            ['nombre' => "VALDIVIA", 'departamento_id' => 2],
            ['nombre' => "VALPARAISO", 'departamento_id' => 2],
            ['nombre' => "VEGACHI", 'departamento_id' => 2],
            ['nombre' => "VENECIA", 'departamento_id' => 2],
            ['nombre' => "VIGIA DEL FUERTE", 'departamento_id' => 2],
            ['nombre' => "YALI", 'departamento_id' => 2],
            ['nombre' => "YARUMAL", 'departamento_id' => 2],
            ['nombre' => "YOLOMBO", 'departamento_id' => 2],
            ['nombre' => "YONDO", 'departamento_id' => 2],
            ['nombre' => "ZARAGOZA", 'departamento_id' => 2],
            ['nombre' => "ARAUCA", 'departamento_id' => 3],
            ['nombre' => "ARAUQUITA", 'departamento_id' => 3],
            ['nombre' => "CRAVO NORTE", 'departamento_id' => 3],
            ['nombre' => "FORTUL", 'departamento_id' => 3],
            ['nombre' => "PUERTO RONDON", 'departamento_id' => 3],
            ['nombre' => "SARAVENA", 'departamento_id' => 3],
            ['nombre' => "TAME", 'departamento_id' => 3],
            ['nombre' => "BARANOA", 'departamento_id' => 4],
            ['nombre' => "BARRANQUILLA", 'departamento_id' => 4],
            ['nombre' => "CAMPO DE LA CRUZ", 'departamento_id' => 4],
            ['nombre' => "CANDELARIA", 'departamento_id' => 4],
            ['nombre' => "GALAPA", 'departamento_id' => 4],
            ['nombre' => "JUAN DE ACOSTA", 'departamento_id' => 4],
            ['nombre' => "LURUACO", 'departamento_id' => 4],
            ['nombre' => "MALAMBO", 'departamento_id' => 4],
            ['nombre' => "MANATI", 'departamento_id' => 4],
            ['nombre' => "PALMAR DE VARELA", 'departamento_id' => 4],
            ['nombre' => "PIOJO", 'departamento_id' => 4],
            ['nombre' => "POLO NUEVO", 'departamento_id' => 4],
            ['nombre' => "PONEDERA", 'departamento_id' => 4],
            ['nombre' => "PUERTO COLOMBIA", 'departamento_id' => 4],
            ['nombre' => "REPELON", 'departamento_id' => 4],
            ['nombre' => "SABANAGRANDE", 'departamento_id' => 4],
            ['nombre' => "SABANALARGA", 'departamento_id' => 4],
            ['nombre' => "SANTA LUCIA", 'departamento_id' => 4],
            ['nombre' => "SANTO TOMAS", 'departamento_id' => 4],
            ['nombre' => "SOLEDAD", 'departamento_id' => 4],
            ['nombre' => "SUAN", 'departamento_id' => 4],
            ['nombre' => "TUBARA", 'departamento_id' => 4],
            ['nombre' => "USIACURI", 'departamento_id' => 4],
            ['nombre' => "BOGOTÁ DC", 'departamento_id' => 5],
            ['nombre' => "ACHI", 'departamento_id' => 6],
            ['nombre' => "ALTOS DEL ROSARIO", 'departamento_id' => 6],
            ['nombre' => "ARENAL", 'departamento_id' => 6],
            ['nombre' => "ARJONA", 'departamento_id' => 6],
            ['nombre' => "ARROYOHONDO", 'departamento_id' => 6],
            ['nombre' => "BARRANCO DE LOBA", 'departamento_id' => 6],
            ['nombre' => "CALAMAR", 'departamento_id' => 6],
            ['nombre' => "CANTAGALLO", 'departamento_id' => 6],
            ['nombre' => "CARTAGENA DE INDIAS", 'departamento_id' => 6],
            ['nombre' => "CICUCO", 'departamento_id' => 6],
            ['nombre' => "CLEMENCIA", 'departamento_id' => 6],
            ['nombre' => "CORDOBA", 'departamento_id' => 6],
            ['nombre' => "EL CARMEN DE BOLIVAR", 'departamento_id' => 6],
            ['nombre' => "EL GUAMO", 'departamento_id' => 6],
            ['nombre' => "EL PENION", 'departamento_id' => 6],
            ['nombre' => "HATILLO DE LOBA", 'departamento_id' => 6],
            ['nombre' => "MAGANGUE", 'departamento_id' => 6],
            ['nombre' => "MAHATES", 'departamento_id' => 6],
            ['nombre' => "MARGARITA", 'departamento_id' => 6],
            ['nombre' => "MARIA LA BAJA", 'departamento_id' => 6],
            ['nombre' => "MONTECRISTO", 'departamento_id' => 6],
            ['nombre' => "MORALES", 'departamento_id' => 6],
            ['nombre' => "PINILLOS", 'departamento_id' => 6],
            ['nombre' => "REGIDOR", 'departamento_id' => 6],
            ['nombre' => "RIO VIEJO", 'departamento_id' => 6],
            ['nombre' => "SAN CRISTOBAL", 'departamento_id' => 6],
            ['nombre' => "SAN ESTANISLAO", 'departamento_id' => 6],
            ['nombre' => "SAN FERNANDO", 'departamento_id' => 6],
            ['nombre' => "SAN JACINTO", 'departamento_id' => 6],
            ['nombre' => "SAN JACINTO DEL CAUCA", 'departamento_id' => 6],
            ['nombre' => "SAN JUAN DE NEPOMUCENO", 'departamento_id' => 6],
            ['nombre' => "SAN MARTÍN DE LOBA", 'departamento_id' => 6],
            ['nombre' => "SAN PABLO NORTE", 'departamento_id' => 6],
            ['nombre' => "SANTA CATALINA", 'departamento_id' => 6],
            ['nombre' => "SANTA CRUZ DE MOMPOX", 'departamento_id' => 6],
            ['nombre' => "SANTA ROSA", 'departamento_id' => 6],
            ['nombre' => "SANTA ROSA DEL SUR", 'departamento_id' => 6],
            ['nombre' => "SIMITI", 'departamento_id' => 6],
            ['nombre' => "SOPLAVIENTO", 'departamento_id' => 6],
            ['nombre' => "TALAIGUA NUEVO", 'departamento_id' => 6],
            ['nombre' => "TUQUISIO", 'departamento_id' => 6],
            ['nombre' => "TURBACO", 'departamento_id' => 6],
            ['nombre' => "TURBANA", 'departamento_id' => 6],
            ['nombre' => "VILLANUEVA", 'departamento_id' => 6],
            ['nombre' => "ZAMBRANO", 'departamento_id' => 6],
            ['nombre' => "ALMEIDA", 'departamento_id' => 7],
            ['nombre' => "AQUITANIA", 'departamento_id' => 7],
            ['nombre' => "ARCABUCO", 'departamento_id' => 7],
            ['nombre' => "BELÉN", 'departamento_id' => 7],
            ['nombre' => "BERBEO", 'departamento_id' => 7],
            ['nombre' => "BETÉITIVA", 'departamento_id' => 7],
            ['nombre' => "BOAVITA", 'departamento_id' => 7],
            ['nombre' => "BOYACÁ", 'departamento_id' => 7],
            ['nombre' => "BRICEÑO", 'departamento_id' => 7],
            ['nombre' => "BUENAVISTA", 'departamento_id' => 7],
            ['nombre' => "BUSBANZÁ", 'departamento_id' => 7],
            ['nombre' => "CALDAS", 'departamento_id' => 7],
            ['nombre' => "CAMPOHERMOSO", 'departamento_id' => 7],
            ['nombre' => "CERINZA", 'departamento_id' => 7],
            ['nombre' => "CHINAVITA", 'departamento_id' => 7],
            ['nombre' => "CHIQUINQUIRÁ", 'departamento_id' => 7],
            ['nombre' => "CHÍQUIZA", 'departamento_id' => 7],
            ['nombre' => "CHISCAS", 'departamento_id' => 7],
            ['nombre' => "CHITA", 'departamento_id' => 7],
            ['nombre' => "CHITARAQUE", 'departamento_id' => 7],
            ['nombre' => "CHIVATÁ", 'departamento_id' => 7],
            ['nombre' => "CHIVOR", 'departamento_id' => 7],
            ['nombre' => "CIÉNEGA", 'departamento_id' => 7],
            ['nombre' => "CÓMBITA", 'departamento_id' => 7],
            ['nombre' => "COPER", 'departamento_id' => 7],
            ['nombre' => "CORRALES", 'departamento_id' => 7],
            ['nombre' => "COVARACHÍA", 'departamento_id' => 7],
            ['nombre' => "CUBARA", 'departamento_id' => 7],
            ['nombre' => "CUCAITA", 'departamento_id' => 7],
            ['nombre' => "CUITIVA", 'departamento_id' => 7],
            ['nombre' => "DUITAMA", 'departamento_id' => 7],
            ['nombre' => "EL COCUY", 'departamento_id' => 7],
            ['nombre' => "EL ESPINO", 'departamento_id' => 7],
            ['nombre' => "FIRAVITOBA", 'departamento_id' => 7],
            ['nombre' => "FLORESTA", 'departamento_id' => 7],
            ['nombre' => "GACHANTIVÁ", 'departamento_id' => 7],
            ['nombre' => "GÁMEZA", 'departamento_id' => 7],
            ['nombre' => "GARAGOA", 'departamento_id' => 7],
            ['nombre' => "GUACAMAYAS", 'departamento_id' => 7],
            ['nombre' => "GUATEQUE", 'departamento_id' => 7],
            ['nombre' => "GUAYATÁ", 'departamento_id' => 7],
            ['nombre' => "GÜICÁN", 'departamento_id' => 7],
            ['nombre' => "IZA", 'departamento_id' => 7],
            ['nombre' => "JENESANO", 'departamento_id' => 7],
            ['nombre' => "JERICÓ", 'departamento_id' => 7],
            ['nombre' => "LA CAPILLA", 'departamento_id' => 7],
            ['nombre' => "LA UVITA", 'departamento_id' => 7],
            ['nombre' => "LA VICTORIA", 'departamento_id' => 7],
            ['nombre' => "LABRANZAGRANDE", 'departamento_id' => 7],
            ['nombre' => "MACANAL", 'departamento_id' => 7],
            ['nombre' => "MARIPÍ", 'departamento_id' => 7],
            ['nombre' => "MIRAFLORES", 'departamento_id' => 7],
            ['nombre' => "MONGUA", 'departamento_id' => 7],
            ['nombre' => "MONGUÍ", 'departamento_id' => 7],
            ['nombre' => "MONIQUIRÁ", 'departamento_id' => 7],
            ['nombre' => "MOTAVITA", 'departamento_id' => 7],
            ['nombre' => "MUZO", 'departamento_id' => 7],
            ['nombre' => "NOBSA", 'departamento_id' => 7],
            ['nombre' => "NUEVO COLÓN", 'departamento_id' => 7],
            ['nombre' => "OICATÁ", 'departamento_id' => 7],
            ['nombre' => "OTANCHE", 'departamento_id' => 7],
            ['nombre' => "PACHAVITA", 'departamento_id' => 7],
            ['nombre' => "PÁEZ", 'departamento_id' => 7],
            ['nombre' => "PAIPA", 'departamento_id' => 7],
            ['nombre' => "PAJARITO", 'departamento_id' => 7],
            ['nombre' => "PANQUEBA", 'departamento_id' => 7],
            ['nombre' => "PAUNA", 'departamento_id' => 7],
            ['nombre' => "PAYA", 'departamento_id' => 7],
            ['nombre' => "PAZ DE RÍO", 'departamento_id' => 7],
            ['nombre' => "PESCA", 'departamento_id' => 7],
            ['nombre' => "PISBA", 'departamento_id' => 7],
            ['nombre' => "PUERTO BOYACA", 'departamento_id' => 7],
            ['nombre' => "QUÍPAMA", 'departamento_id' => 7],
            ['nombre' => "RAMIRIQUÍ", 'departamento_id' => 7],
            ['nombre' => "RÁQUIRA", 'departamento_id' => 7],
            ['nombre' => "RONDÓN", 'departamento_id' => 7],
            ['nombre' => "SABOYÁ", 'departamento_id' => 7],
            ['nombre' => "SÁCHICA", 'departamento_id' => 7],
            ['nombre' => "SAMACÁ", 'departamento_id' => 7],
            ['nombre' => "SAN EDUARDO", 'departamento_id' => 7],
            ['nombre' => "SAN JOSÉ DE PARE", 'departamento_id' => 7],
            ['nombre' => "SAN LUIS DE GACENO", 'departamento_id' => 7],
            ['nombre' => "SAN MATEO", 'departamento_id' => 7],
            ['nombre' => "SAN MIGUEL DE SEMA", 'departamento_id' => 7],
            ['nombre' => "SAN PABLO DE BORBUR", 'departamento_id' => 7],
            ['nombre' => "SANTA MARÍA", 'departamento_id' => 7],
            ['nombre' => "SANTA ROSA DE VITERBO", 'departamento_id' => 7],
            ['nombre' => "SANTA SOFÍA", 'departamento_id' => 7],
            ['nombre' => "SANTANA", 'departamento_id' => 7],
            ['nombre' => "SATIVANORTE", 'departamento_id' => 7],
            ['nombre' => "SATIVASUR", 'departamento_id' => 7],
            ['nombre' => "SIACHOQUE", 'departamento_id' => 7],
            ['nombre' => "SOATÁ", 'departamento_id' => 7],
            ['nombre' => "SOCHA", 'departamento_id' => 7],
            ['nombre' => "SOCOTÁ", 'departamento_id' => 7],
            ['nombre' => "SOGAMOSO", 'departamento_id' => 7],
            ['nombre' => "SOMONDOCO", 'departamento_id' => 7],
            ['nombre' => "SORA", 'departamento_id' => 7],
            ['nombre' => "SORACÁ", 'departamento_id' => 7],
            ['nombre' => "SOTAQUIRÁ", 'departamento_id' => 7],
            ['nombre' => "SUSACÓN", 'departamento_id' => 7],
            ['nombre' => "SUTAMARCHÁN", 'departamento_id' => 7],
            ['nombre' => "SUTATENZA", 'departamento_id' => 7],
            ['nombre' => "TASCO", 'departamento_id' => 7],
            ['nombre' => "TENZA", 'departamento_id' => 7],
            ['nombre' => "TIBANÁ", 'departamento_id' => 7],
            ['nombre' => "TIBASOSA", 'departamento_id' => 7],
            ['nombre' => "TINJACÁ", 'departamento_id' => 7],
            ['nombre' => "TIPACOQUE", 'departamento_id' => 7],
            ['nombre' => "TOCA", 'departamento_id' => 7],
            ['nombre' => "TOGÜÍ", 'departamento_id' => 7],
            ['nombre' => "TÓPAGA", 'departamento_id' => 7],
            ['nombre' => "TOTA", 'departamento_id' => 7],
            ['nombre' => "TUNJA", 'departamento_id' => 7],
            ['nombre' => "TUNUNGUÁ", 'departamento_id' => 7],
            ['nombre' => "TURMEQUÉ", 'departamento_id' => 7],
            ['nombre' => "TUTA", 'departamento_id' => 7],
            ['nombre' => "TUTAZÁ", 'departamento_id' => 7],
            ['nombre' => "UMBITA", 'departamento_id' => 7],
            ['nombre' => "VENTAQUEMADA", 'departamento_id' => 7],
            ['nombre' => "VILLA DE LEYVA", 'departamento_id' => 7],
            ['nombre' => "VIRACACHÁ", 'departamento_id' => 7],
            ['nombre' => "ZETAQUIRA", 'departamento_id' => 7],
            ['nombre' => "AGUADAS", 'departamento_id' => 8],
            ['nombre' => "ANSERMA", 'departamento_id' => 8],
            ['nombre' => "ARANZAZU", 'departamento_id' => 8],
            ['nombre' => "BELALCAZAR", 'departamento_id' => 8],
            ['nombre' => "CHINCHINÁ", 'departamento_id' => 8],
            ['nombre' => "FILADELFIA", 'departamento_id' => 8],
            ['nombre' => "LA DORADA", 'departamento_id' => 8],
            ['nombre' => "LA MERCED", 'departamento_id' => 8],
            ['nombre' => "MANIZALES", 'departamento_id' => 8],
            ['nombre' => "MANZANARES", 'departamento_id' => 8],
            ['nombre' => "MARMATO", 'departamento_id' => 8],
            ['nombre' => "MARQUETALIA", 'departamento_id' => 8],
            ['nombre' => "MARULANDA", 'departamento_id' => 8],
            ['nombre' => "NEIRA", 'departamento_id' => 8],
            ['nombre' => "NORCASIA", 'departamento_id' => 8],
            ['nombre' => "PACORA", 'departamento_id' => 8],
            ['nombre' => "PALESTINA", 'departamento_id' => 8],
            ['nombre' => "PENSILVANIA", 'departamento_id' => 8],
            ['nombre' => "RIOSUCIO", 'departamento_id' => 8],
            ['nombre' => "RISARALDA", 'departamento_id' => 8],
            ['nombre' => "SALAMINA", 'departamento_id' => 8],
            ['nombre' => "SAMANA", 'departamento_id' => 8],
            ['nombre' => "SAN JOSE", 'departamento_id' => 8],
            ['nombre' => "SUPÍA", 'departamento_id' => 8],
            ['nombre' => "VICTORIA", 'departamento_id' => 8],
            ['nombre' => "VILLAMARÍA", 'departamento_id' => 8],
            ['nombre' => "VITERBO", 'departamento_id' => 8],
            ['nombre' => "ALBANIA", 'departamento_id' => 9],
            ['nombre' => "BELÉN DE LOS ANDAQUIES", 'departamento_id' => 9],
            ['nombre' => "CARTAGENA DEL CHAIRA", 'departamento_id' => 9],
            ['nombre' => "CURILLO", 'departamento_id' => 9],
            ['nombre' => "EL DONCELLO", 'departamento_id' => 9],
            ['nombre' => "EL PAUJIL", 'departamento_id' => 9],
            ['nombre' => "FLORENCIA", 'departamento_id' => 9],
            ['nombre' => "LA MONTAÑITA", 'departamento_id' => 9],
            ['nombre' => "MILÁN", 'departamento_id' => 9],
            ['nombre' => "MORELIA", 'departamento_id' => 9],
            ['nombre' => "PUERTO RICO", 'departamento_id' => 9],
            ['nombre' => "SAN JOSÉ DEL FRAGUA", 'departamento_id' => 9],
            ['nombre' => "SAN VICENTE DEL CAGUAN", 'departamento_id' => 9],
            ['nombre' => "SOLANO", 'departamento_id' => 9],
            ['nombre' => "SOLITA", 'departamento_id' => 9],
            ['nombre' => "VALPARAÍSO", 'departamento_id' => 9],
            ['nombre' => "AGUAZUL", 'departamento_id' => 10],
            ['nombre' => "CHAMEZA", 'departamento_id' => 10],
            ['nombre' => "HATO COROZAL", 'departamento_id' => 10],
            ['nombre' => "LA SALINA", 'departamento_id' => 10],
            ['nombre' => "MANÍ", 'departamento_id' => 10],
            ['nombre' => "MONTERREY", 'departamento_id' => 10],
            ['nombre' => "NUNCHIA", 'departamento_id' => 10],
            ['nombre' => "OROCUE", 'departamento_id' => 10],
            ['nombre' => "PAZ DE ARIPORO", 'departamento_id' => 10],
            ['nombre' => "PORE", 'departamento_id' => 10],
            ['nombre' => "RECETOR", 'departamento_id' => 10],
            ['nombre' => "SABANALARGA", 'departamento_id' => 10],
            ['nombre' => "SACAMA", 'departamento_id' => 10],
            ['nombre' => "SAN LUIS DE PALENQUE", 'departamento_id' => 10],
            ['nombre' => "TAMARA", 'departamento_id' => 10],
            ['nombre' => "TAURAMENA", 'departamento_id' => 10],
            ['nombre' => "TRINIDAD", 'departamento_id' => 10],
            ['nombre' => "VILLANUEVA", 'departamento_id' => 10],
            ['nombre' => "YOPAL", 'departamento_id' => 10],
            ['nombre' => "ALMAGUER", 'departamento_id' => 11],
            ['nombre' => "ARGELIA", 'departamento_id' => 11],
            ['nombre' => "BALBOA", 'departamento_id' => 11],
            ['nombre' => "BOLÍVAR", 'departamento_id' => 11],
            ['nombre' => "BUENOS AIRES", 'departamento_id' => 11],
            ['nombre' => "CAJIBIO", 'departamento_id' => 11],
            ['nombre' => "CALDONO", 'departamento_id' => 11],
            ['nombre' => "CALOTO", 'departamento_id' => 11],
            ['nombre' => "CORINTO", 'departamento_id' => 11],
            ['nombre' => "EL TAMBO", 'departamento_id' => 11],
            ['nombre' => "FLORENCIA", 'departamento_id' => 11],
            ['nombre' => "GUAPI", 'departamento_id' => 11],
            ['nombre' => "INZA", 'departamento_id' => 11],
            ['nombre' => "JAMBALÓ", 'departamento_id' => 11],
            ['nombre' => "LA SIERRA", 'departamento_id' => 11],
            ['nombre' => "LA VEGA", 'departamento_id' => 11],
            ['nombre' => "LÓPEZ", 'departamento_id' => 11],
            ['nombre' => "MERCADERES", 'departamento_id' => 11],
            ['nombre' => "MIRANDA", 'departamento_id' => 11],
            ['nombre' => "MORALES", 'departamento_id' => 11],
            ['nombre' => "PADILLA", 'departamento_id' => 11],
            ['nombre' => "PÁEZ", 'departamento_id' => 11],
            ['nombre' => "PATÍA", 'departamento_id' => 11],
            ['nombre' => "PIAMONTE", 'departamento_id' => 11],
            ['nombre' => "PIENDAMO", 'departamento_id' => 11],
            ['nombre' => "POPAYÁN", 'departamento_id' => 11],
            ['nombre' => "PUERTO TEJADA", 'departamento_id' => 11],
            ['nombre' => "PURACE", 'departamento_id' => 11],
            ['nombre' => "ROSAS", 'departamento_id' => 11],
            ['nombre' => "SAN SEBASTIÁN", 'departamento_id' => 11],
            ['nombre' => "SANTA ROSA", 'departamento_id' => 11],
            ['nombre' => "SANTANDER DE QUILICHAO", 'departamento_id' => 11],
            ['nombre' => "SILVIA", 'departamento_id' => 11],
            ['nombre' => "SOTARA", 'departamento_id' => 11],
            ['nombre' => "SUÁREZ", 'departamento_id' => 11],
            ['nombre' => "SUCRE", 'departamento_id' => 11],
            ['nombre' => "TIMBÍO", 'departamento_id' => 11],
            ['nombre' => "TIMBIQUÍ", 'departamento_id' => 11],
            ['nombre' => "TORIBIO", 'departamento_id' => 11],
            ['nombre' => "TOTORO", 'departamento_id' => 11],
            ['nombre' => "VILLA RICA", 'departamento_id' => 11],
            ['nombre' => "AGUACHICA", 'departamento_id' => 12],
            ['nombre' => "AGUSTÍN CODAZZI", 'departamento_id' => 12],
            ['nombre' => "ASTREA", 'departamento_id' => 12],
            ['nombre' => "BECERRIL", 'departamento_id' => 12],
            ['nombre' => "BOSCONIA", 'departamento_id' => 12],
            ['nombre' => "CHIMICHAGUA", 'departamento_id' => 12],
            ['nombre' => "CHIRIGUANÁ", 'departamento_id' => 12],
            ['nombre' => "CURUMANÍ", 'departamento_id' => 12],
            ['nombre' => "EL COPEY", 'departamento_id' => 12],
            ['nombre' => "EL PASO", 'departamento_id' => 12],
            ['nombre' => "GAMARRA", 'departamento_id' => 12],
            ['nombre' => "GONZÁLEZ", 'departamento_id' => 12],
            ['nombre' => "LA GLORIA", 'departamento_id' => 12],
            ['nombre' => "LA JAGUA DE IBIRICO", 'departamento_id' => 12],
            ['nombre' => "LA PAZ", 'departamento_id' => 12],
            ['nombre' => "MANAURE BALCÓN DEL CESAR", 'departamento_id' => 12],
            ['nombre' => "PAILITAS", 'departamento_id' => 12],
            ['nombre' => "PELAYA", 'departamento_id' => 12],
            ['nombre' => "PUEBLO BELLO", 'departamento_id' => 12],
            ['nombre' => "RÍO DE ORO", 'departamento_id' => 12],
            ['nombre' => "SAN ALBERTO", 'departamento_id' => 12],
            ['nombre' => "SAN DIEGO", 'departamento_id' => 12],
            ['nombre' => "SAN MARTÍN", 'departamento_id' => 12],
            ['nombre' => "TAMALAMEQUE", 'departamento_id' => 12],
            ['nombre' => "VALLEDUPAR", 'departamento_id' => 12],
            ['nombre' => "ACANDI", 'departamento_id' => 13],
            ['nombre' => "ALTO BAUDO", 'departamento_id' => 13],
            ['nombre' => "ATRATO", 'departamento_id' => 13],
            ['nombre' => "BAGADO", 'departamento_id' => 13],
            ['nombre' => "BAHIA SOLANO", 'departamento_id' => 13],
            ['nombre' => "BAJO BAUDO", 'departamento_id' => 13],
            ['nombre' => "BOJAYA", 'departamento_id' => 13],
            ['nombre' => "CARMEN DEL DARIEN", 'departamento_id' => 13],
            ['nombre' => "CERTEGUI", 'departamento_id' => 13],
            ['nombre' => "CONDOTO", 'departamento_id' => 13],
            ['nombre' => "EL CANTÓN DE SAN PABLO", 'departamento_id' => 13],
            ['nombre' => "EL CARMEN DE ATRATO", 'departamento_id' => 13],
            ['nombre' => "EL LITORAL DEL SAN JUAN", 'departamento_id' => 13],
            ['nombre' => "ISTMINA", 'departamento_id' => 13],
            ['nombre' => "JURADO", 'departamento_id' => 13],
            ['nombre' => "LLORO", 'departamento_id' => 13],
            ['nombre' => "MEDIO ATRATO", 'departamento_id' => 13],
            ['nombre' => "MEDIO BAUDO", 'departamento_id' => 13],
            ['nombre' => "MEDIO SAN JUAN", 'departamento_id' => 13],
            ['nombre' => "NOVITA", 'departamento_id' => 13],
            ['nombre' => "NUQUI", 'departamento_id' => 13],
            ['nombre' => "QUIBDO", 'departamento_id' => 13],
            ['nombre' => "RIO IRO", 'departamento_id' => 13],
            ['nombre' => "RIO QUITO", 'departamento_id' => 13],
            ['nombre' => "RIOSUCIO", 'departamento_id' => 13],
            ['nombre' => "SAN JOSE DEL PALMAR", 'departamento_id' => 13],
            ['nombre' => "SIPI", 'departamento_id' => 13],
            ['nombre' => "TADO", 'departamento_id' => 13],
            ['nombre' => "UNGUIA", 'departamento_id' => 13],
            ['nombre' => "UNIÓN PANAMERICANA", 'departamento_id' => 13],
            ['nombre' => "AYAPEL", 'departamento_id' => 14],
            ['nombre' => "BELÉN DE BAJIRÁ", 'departamento_id' => 14],
            ['nombre' => "BUENAVISTA", 'departamento_id' => 14],
            ['nombre' => "CANALETE", 'departamento_id' => 14],
            ['nombre' => "CERETÉ", 'departamento_id' => 14],
            ['nombre' => "CHIMA", 'departamento_id' => 14],
            ['nombre' => "CHINÚ", 'departamento_id' => 14],
            ['nombre' => "CIENAGA DE ORO", 'departamento_id' => 14],
            ['nombre' => "COTORRA", 'departamento_id' => 14],
            ['nombre' => "LA APARTADA", 'departamento_id' => 14],
            ['nombre' => "LORICA", 'departamento_id' => 14],
            ['nombre' => "LOS CÓRDOBAS", 'departamento_id' => 14],
            ['nombre' => "MOMIL", 'departamento_id' => 14],
            ['nombre' => "MONTELÍBANO", 'departamento_id' => 14],
            ['nombre' => "MONTERÍA", 'departamento_id' => 14],
            ['nombre' => "MOÑITOS", 'departamento_id' => 14],
            ['nombre' => "PLANETA RICA", 'departamento_id' => 14],
            ['nombre' => "PUEBLO NUEVO", 'departamento_id' => 14],
            ['nombre' => "PUERTO ESCONDIDO", 'departamento_id' => 14],
            ['nombre' => "PUERTO LIBERTADOR", 'departamento_id' => 14],
            ['nombre' => "PURÍSIMA", 'departamento_id' => 14],
            ['nombre' => "SAHAGÚN", 'departamento_id' => 14],
            ['nombre' => "SAN ANDRÉS SOTAVENTO", 'departamento_id' => 14],
            ['nombre' => "SAN ANTERO", 'departamento_id' => 14],
            ['nombre' => "SAN BERNARDO DEL VIENTO", 'departamento_id' => 14],
            ['nombre' => "SAN CARLOS", 'departamento_id' => 14],
            ['nombre' => "SAN PELAYO", 'departamento_id' => 14],
            ['nombre' => "TIERRALTA", 'departamento_id' => 14],
            ['nombre' => "VALENCIA", 'departamento_id' => 14],
            ['nombre' => "AGUA DE DIOS", 'departamento_id' => 15],
            ['nombre' => "ALBAN", 'departamento_id' => 15],
            ['nombre' => "ANAPOIMA", 'departamento_id' => 15],
            ['nombre' => "ANOLAIMA", 'departamento_id' => 15],
            ['nombre' => "APULO", 'departamento_id' => 15],
            ['nombre' => "ARBELAEZ", 'departamento_id' => 15],
            ['nombre' => "BELTRÁN", 'departamento_id' => 15],
            ['nombre' => "BITUIMA", 'departamento_id' => 15],
            ['nombre' => "BOJACÁ", 'departamento_id' => 15],
            ['nombre' => "CABRERA", 'departamento_id' => 15],
            ['nombre' => "CACHIPAY", 'departamento_id' => 15],
            ['nombre' => "CAJICÁ", 'departamento_id' => 15],
            ['nombre' => "CAPARRAPÍ", 'departamento_id' => 15],
            ['nombre' => "CAQUEZA", 'departamento_id' => 15],
            ['nombre' => "CARMEN DE CARUPA", 'departamento_id' => 15],
            ['nombre' => "CHAGUANÍ", 'departamento_id' => 15],
            ['nombre' => "CHIA", 'departamento_id' => 15],
            ['nombre' => "CHIPAQUE", 'departamento_id' => 15],
            ['nombre' => "CHOACHÍ", 'departamento_id' => 15],
            ['nombre' => "CHOCONTÁ", 'departamento_id' => 15],
            ['nombre' => "COGUA", 'departamento_id' => 15],
            ['nombre' => "COTA", 'departamento_id' => 15],
            ['nombre' => "CUCUNUBÁ", 'departamento_id' => 15],
            ['nombre' => "EL COLEGIO", 'departamento_id' => 15],
            ['nombre' => "EL PEÑÓN", 'departamento_id' => 15],
            ['nombre' => "EL ROSAL", 'departamento_id' => 15],
            ['nombre' => "FACATATIVA", 'departamento_id' => 15],
            ['nombre' => "FÓMEQUE", 'departamento_id' => 15],
            ['nombre' => "FOSCA", 'departamento_id' => 15],
            ['nombre' => "FUNZA", 'departamento_id' => 15],
            ['nombre' => "FÚQUENE", 'departamento_id' => 15],
            ['nombre' => "FUSAGASUGA", 'departamento_id' => 15],
            ['nombre' => "GACHALÁ", 'departamento_id' => 15],
            ['nombre' => "GACHANCIPÁ", 'departamento_id' => 15],
            ['nombre' => "GACHETA", 'departamento_id' => 15],
            ['nombre' => "GAMA", 'departamento_id' => 15],
            ['nombre' => "GIRARDOT", 'departamento_id' => 15],
            ['nombre' => "GRANADA", 'departamento_id' => 15],
            ['nombre' => "GUACHETÁ", 'departamento_id' => 15],
            ['nombre' => "GUADUAS", 'departamento_id' => 15],
            ['nombre' => "GUASCA", 'departamento_id' => 15],
            ['nombre' => "GUATAQUÍ", 'departamento_id' => 15],
            ['nombre' => "GUATAVITA", 'departamento_id' => 15],
            ['nombre' => "GUAYABAL DE SIQUIMA", 'departamento_id' => 15],
            ['nombre' => "GUAYABETAL", 'departamento_id' => 15],
            ['nombre' => "GUTIÉRREZ", 'departamento_id' => 15],
            ['nombre' => "JERUSALÉN", 'departamento_id' => 15],
            ['nombre' => "JUNÍN", 'departamento_id' => 15],
            ['nombre' => "LA CALERA", 'departamento_id' => 15],
            ['nombre' => "LA MESA", 'departamento_id' => 15],
            ['nombre' => "LA PALMA", 'departamento_id' => 15],
            ['nombre' => "LA PEÑA", 'departamento_id' => 15],
            ['nombre' => "LA VEGA", 'departamento_id' => 15],
            ['nombre' => "LENGUAZAQUE", 'departamento_id' => 15],
            ['nombre' => "MACHETÁ", 'departamento_id' => 15],
            ['nombre' => "MADRID", 'departamento_id' => 15],
            ['nombre' => "MANTA", 'departamento_id' => 15],
            ['nombre' => "MEDINA", 'departamento_id' => 15],
            ['nombre' => "MOSQUERA", 'departamento_id' => 15],
            ['nombre' => "NARIÑO", 'departamento_id' => 15],
            ['nombre' => "NEMOCÓN", 'departamento_id' => 15],
            ['nombre' => "NILO", 'departamento_id' => 15],
            ['nombre' => "NIMAIMA", 'departamento_id' => 15],
            ['nombre' => "NOCAIMA", 'departamento_id' => 15],
            ['nombre' => "PACHO", 'departamento_id' => 15],
            ['nombre' => "PAIME", 'departamento_id' => 15],
            ['nombre' => "PANDI", 'departamento_id' => 15],
            ['nombre' => "PARATEBUENO", 'departamento_id' => 15],
            ['nombre' => "PASCA", 'departamento_id' => 15],
            ['nombre' => "PUERTO SALGAR", 'departamento_id' => 15],
            ['nombre' => "PULÍ", 'departamento_id' => 15],
            ['nombre' => "QUEBRADANEGRA", 'departamento_id' => 15],
            ['nombre' => "QUETAME", 'departamento_id' => 15],
            ['nombre' => "QUIPILE", 'departamento_id' => 15],
            ['nombre' => "RICAURTE", 'departamento_id' => 15],
            ['nombre' => "SAN ANTONIO DEL TEQUENDAMA", 'departamento_id' => 15],
            ['nombre' => "SAN BERNARDO", 'departamento_id' => 15],
            ['nombre' => "SAN CAYETANO", 'departamento_id' => 15],
            ['nombre' => "SAN FRANCISCO", 'departamento_id' => 15],
            ['nombre' => "SAN JUAN DE RIOSECO", 'departamento_id' => 15],
            ['nombre' => "SASAIMA", 'departamento_id' => 15],
            ['nombre' => "SESQUILÉ", 'departamento_id' => 15],
            ['nombre' => "SIBATÉ", 'departamento_id' => 15],
            ['nombre' => "SILVANIA", 'departamento_id' => 15],
            ['nombre' => "SIMIJACA", 'departamento_id' => 15],
            ['nombre' => "SOACHA", 'departamento_id' => 15],
            ['nombre' => "SOPO", 'departamento_id' => 15],
            ['nombre' => "SUBACHOQUE", 'departamento_id' => 15],
            ['nombre' => "SUESCA", 'departamento_id' => 15],
            ['nombre' => "SUPATÁ", 'departamento_id' => 15],
            ['nombre' => "SUSA", 'departamento_id' => 15],
            ['nombre' => "SUTATAUSA", 'departamento_id' => 15],
            ['nombre' => "TABIO", 'departamento_id' => 15],
            ['nombre' => "TAUSA", 'departamento_id' => 15],
            ['nombre' => "TENA", 'departamento_id' => 15],
            ['nombre' => "TENJO", 'departamento_id' => 15],
            ['nombre' => "TIBACUY", 'departamento_id' => 15],
            ['nombre' => "TIBIRITA", 'departamento_id' => 15],
            ['nombre' => "TOCAIMA", 'departamento_id' => 15],
            ['nombre' => "TOCANCIPÁ", 'departamento_id' => 15],
            ['nombre' => "TOPAIPÍ", 'departamento_id' => 15],
            ['nombre' => "UBALÁ", 'departamento_id' => 15],
            ['nombre' => "UBAQUE", 'departamento_id' => 15],
            ['nombre' => "UBATÉ", 'departamento_id' => 15],
            ['nombre' => "UNE", 'departamento_id' => 15],
            ['nombre' => "UTICA", 'departamento_id' => 15],
            ['nombre' => "VENECIA", 'departamento_id' => 15],
            ['nombre' => "VERGARA", 'departamento_id' => 15],
            ['nombre' => "VIANI", 'departamento_id' => 15],
            ['nombre' => "VILLAGÓMEZ", 'departamento_id' => 15],
            ['nombre' => "VILLAPINZÓN", 'departamento_id' => 15],
            ['nombre' => "VILLETA", 'departamento_id' => 15],
            ['nombre' => "VIOTA", 'departamento_id' => 15],
            ['nombre' => "YACOPÍ", 'departamento_id' => 15],
            ['nombre' => "ZIPACÓN", 'departamento_id' => 15],
            ['nombre' => "ZIPAQUIRÁ", 'departamento_id' => 15],
            ['nombre' => "BARRANCO MINAS", 'departamento_id' => 16],
            ['nombre' => "CACAHUAL", 'departamento_id' => 16],
            ['nombre' => "INÍRIDA", 'departamento_id' => 16],
            ['nombre' => "LA GUADALUPE", 'departamento_id' => 16],
            ['nombre' => "MAPIRIPANA", 'departamento_id' => 16],
            ['nombre' => "MORICHAL", 'departamento_id' => 16],
            ['nombre' => "PANA PANA", 'departamento_id' => 16],
            ['nombre' => "PUERTO COLOMBIA", 'departamento_id' => 16],
            ['nombre' => "SAN FELIPE", 'departamento_id' => 16],
            ['nombre' => "CALAMAR", 'departamento_id' => 17],
            ['nombre' => "EL RETORNO", 'departamento_id' => 17],
            ['nombre' => "MIRAFLORES", 'departamento_id' => 17],
            ['nombre' => "SAN JOSÉ DEL GUAVIARE", 'departamento_id' => 17],
            ['nombre' => "ACEVEDO", 'departamento_id' => 18],
            ['nombre' => "AGRADO", 'departamento_id' => 18],
            ['nombre' => "AIPE", 'departamento_id' => 18],
            ['nombre' => "ALGECIRAS", 'departamento_id' => 18],
            ['nombre' => "ALTAMIRA", 'departamento_id' => 18],
            ['nombre' => "BARAYA", 'departamento_id' => 18],
            ['nombre' => "CAMPOALEGRE", 'departamento_id' => 18],
            ['nombre' => "COLOMBIA", 'departamento_id' => 18],
            ['nombre' => "ELIAS", 'departamento_id' => 18],
            ['nombre' => "GARZÓN", 'departamento_id' => 18],
            ['nombre' => "GIGANTE", 'departamento_id' => 18],
            ['nombre' => "GUADALUPE", 'departamento_id' => 18],
            ['nombre' => "HOBO", 'departamento_id' => 18],
            ['nombre' => "IQUIRA", 'departamento_id' => 18],
            ['nombre' => "ISNOS", 'departamento_id' => 18],
            ['nombre' => "LA ARGENTINA", 'departamento_id' => 18],
            ['nombre' => "LA PLATA", 'departamento_id' => 18],
            ['nombre' => "NATAGA", 'departamento_id' => 18],
            ['nombre' => "NEIVA", 'departamento_id' => 18],
            ['nombre' => "OPORAPA", 'departamento_id' => 18],
            ['nombre' => "PAICOL", 'departamento_id' => 18],
            ['nombre' => "PALERMO", 'departamento_id' => 18],
            ['nombre' => "PALESTINA", 'departamento_id' => 18],
            ['nombre' => "PITAL", 'departamento_id' => 18],
            ['nombre' => "PITALITO", 'departamento_id' => 18],
            ['nombre' => "RIVERA", 'departamento_id' => 18],
            ['nombre' => "SALADOBLANCO", 'departamento_id' => 18],
            ['nombre' => "SAN AGUSTÍN", 'departamento_id' => 18],
            ['nombre' => "SANTA MARIA", 'departamento_id' => 18],
            ['nombre' => "SUAZA", 'departamento_id' => 18],
            ['nombre' => "TARQUI", 'departamento_id' => 18],
            ['nombre' => "TELLO", 'departamento_id' => 18],
            ['nombre' => "TERUEL", 'departamento_id' => 18],
            ['nombre' => "TESALIA", 'departamento_id' => 18],
            ['nombre' => "TIMANA", 'departamento_id' => 18],
            ['nombre' => "VILLAVIEJA", 'departamento_id' => 18],
            ['nombre' => "YAGUARA", 'departamento_id' => 18],
            ['nombre' => "ALBANIA", 'departamento_id' => 19],
            ['nombre' => "BARRANCAS", 'departamento_id' => 19],
            ['nombre' => "DIBULLA", 'departamento_id' => 19],
            ['nombre' => "DISTRACCIÓN", 'departamento_id' => 19],
            ['nombre' => "EL MOLINO", 'departamento_id' => 19],
            ['nombre' => "FONSECA", 'departamento_id' => 19],
            ['nombre' => "HATONUEVO", 'departamento_id' => 19],
            ['nombre' => "LA JAGUA DEL PILAR", 'departamento_id' => 19],
            ['nombre' => "MAICAO", 'departamento_id' => 19],
            ['nombre' => "MANAURE", 'departamento_id' => 19],
            ['nombre' => "RIOHACHA", 'departamento_id' => 19],
            ['nombre' => "SAN JUAN DEL CESAR", 'departamento_id' => 19],
            ['nombre' => "URIBIA", 'departamento_id' => 19],
            ['nombre' => "URUMITA", 'departamento_id' => 19],
            ['nombre' => "VILLANUEVA", 'departamento_id' => 19],
            ['nombre' => "ALGARROBO", 'departamento_id' => 20],
            ['nombre' => "ARACATACA", 'departamento_id' => 20],
            ['nombre' => "ARIGUANI", 'departamento_id' => 20],
            ['nombre' => "CERRO SAN ANTONIO", 'departamento_id' => 20],
            ['nombre' => "CHIBOLO", 'departamento_id' => 20],
            ['nombre' => "CIENAGA", 'departamento_id' => 20],
            ['nombre' => "CONCORDIA", 'departamento_id' => 20],
            ['nombre' => "EL BANCO", 'departamento_id' => 20],
            ['nombre' => "EL PIÑON", 'departamento_id' => 20],
            ['nombre' => "EL RETEN", 'departamento_id' => 20],
            ['nombre' => "FUNDACION", 'departamento_id' => 20],
            ['nombre' => "GUAMAL", 'departamento_id' => 20],
            ['nombre' => "NUEVA GRANADA", 'departamento_id' => 20],
            ['nombre' => "PEDRAZA", 'departamento_id' => 20],
            ['nombre' => "PIJIÑO DEL CARMEN", 'departamento_id' => 20],
            ['nombre' => "PIVIJAY", 'departamento_id' => 20],
            ['nombre' => "PLATO", 'departamento_id' => 20],
            ['nombre' => "PUEBLOVIEJO", 'departamento_id' => 20],
            ['nombre' => "REMOLINO", 'departamento_id' => 20],
            ['nombre' => "SABANAS DE SAN ANGEL", 'departamento_id' => 20],
            ['nombre' => "SALAMINA", 'departamento_id' => 20],
            ['nombre' => "SAN SEBASTIAN DE BUENAVISTA", 'departamento_id' => 20],
            ['nombre' => "SAN ZENON", 'departamento_id' => 20],
            ['nombre' => "SANTA ANA", 'departamento_id' => 20],
            ['nombre' => "SANTA BARBARA DE PINTO", 'departamento_id' => 20],
            ['nombre' => "SANTA MARTA", 'departamento_id' => 20],
            ['nombre' => "SITIONUEVO", 'departamento_id' => 20],
            ['nombre' => "TENERIFE", 'departamento_id' => 20],
            ['nombre' => "ZAPAYAN", 'departamento_id' => 20],
            ['nombre' => "ZONA BANANERA", 'departamento_id' => 20],
            ['nombre' => "ACACIAS", 'departamento_id' => 21],
            ['nombre' => "BARRANCA DE UPIA", 'departamento_id' => 21],
            ['nombre' => "CABUYARO", 'departamento_id' => 21],
            ['nombre' => "CASTILLA LA NUEVA", 'departamento_id' => 21],
            ['nombre' => "CUBARRAL", 'departamento_id' => 21],
            ['nombre' => "CUMARAL", 'departamento_id' => 21],
            ['nombre' => "EL CALVARIO", 'departamento_id' => 21],
            ['nombre' => "EL CASTILLO", 'departamento_id' => 21],
            ['nombre' => "EL DORADO", 'departamento_id' => 21],
            ['nombre' => "FUENTE DE ORO", 'departamento_id' => 21],
            ['nombre' => "GRANADA", 'departamento_id' => 21],
            ['nombre' => "GUAMAL", 'departamento_id' => 21],
            ['nombre' => "LA MACARENA", 'departamento_id' => 21],
            ['nombre' => "LA URIBE", 'departamento_id' => 21],
            ['nombre' => "LEJANÍAS", 'departamento_id' => 21],
            ['nombre' => "MAPIRIPÁN", 'departamento_id' => 21],
            ['nombre' => "MESETAS", 'departamento_id' => 21],
            ['nombre' => "PUERTO CONCORDIA", 'departamento_id' => 21],
            ['nombre' => "PUERTO GAITÁN", 'departamento_id' => 21],
            ['nombre' => "PUERTO LLERAS", 'departamento_id' => 21],
            ['nombre' => "PUERTO LÓPEZ", 'departamento_id' => 21],
            ['nombre' => "PUERTO RICO", 'departamento_id' => 21],
            ['nombre' => "RESTREPO", 'departamento_id' => 21],
            ['nombre' => "SAN CARLOS DE GUAROA", 'departamento_id' => 21],
            ['nombre' => "SAN JUAN DE ARAMA", 'departamento_id' => 21],
            ['nombre' => "SAN JUANITO", 'departamento_id' => 21],
            ['nombre' => "SAN MARTÍN", 'departamento_id' => 21],
            ['nombre' => "VILLAVICENCIO", 'departamento_id' => 21],
            ['nombre' => "VISTA HERMOSA", 'departamento_id' => 21],
            ['nombre' => "ALBAN", 'departamento_id' => 22],
            ['nombre' => "ALDANA", 'departamento_id' => 22],
            ['nombre' => "ANCUYA", 'departamento_id' => 22],
            ['nombre' => "ARBOLEDA", 'departamento_id' => 22],
            ['nombre' => "BARBACOAS", 'departamento_id' => 22],
            ['nombre' => "BELEN", 'departamento_id' => 22],
            ['nombre' => "BUESACO", 'departamento_id' => 22],
            ['nombre' => "CHACHAGUI", 'departamento_id' => 22],
            ['nombre' => "COLON", 'departamento_id' => 22],
            ['nombre' => "CONSACA", 'departamento_id' => 22],
            ['nombre' => "CONTADERO", 'departamento_id' => 22],
            ['nombre' => "CORDOBA", 'departamento_id' => 22],
            ['nombre' => "CUASPUD", 'departamento_id' => 22],
            ['nombre' => "CUMBAL", 'departamento_id' => 22],
            ['nombre' => "CUMBITARA", 'departamento_id' => 22],
            ['nombre' => "EL CHARCO", 'departamento_id' => 22],
            ['nombre' => "EL PEÑOL", 'departamento_id' => 22],
            ['nombre' => "EL ROSARIO", 'departamento_id' => 22],
            ['nombre' => "EL TABLÓN DE GÓMEZ", 'departamento_id' => 22],
            ['nombre' => "EL TAMBO", 'departamento_id' => 22],
            ['nombre' => "FRANCISCO PIZARRO", 'departamento_id' => 22],
            ['nombre' => "FUNES", 'departamento_id' => 22],
            ['nombre' => "GUACHUCAL", 'departamento_id' => 22],
            ['nombre' => "GUAITARILLA", 'departamento_id' => 22],
            ['nombre' => "GUALMATAN", 'departamento_id' => 22],
            ['nombre' => "ILES", 'departamento_id' => 22],
            ['nombre' => "IMUES", 'departamento_id' => 22],
            ['nombre' => "IPIALES", 'departamento_id' => 22],
            ['nombre' => "LA CRUZ", 'departamento_id' => 22],
            ['nombre' => "LA FLORIDA", 'departamento_id' => 22],
            ['nombre' => "LA LLANADA", 'departamento_id' => 22],
            ['nombre' => "LA TOLA", 'departamento_id' => 22],
            ['nombre' => "LA UNION", 'departamento_id' => 22],
            ['nombre' => "LEIVA", 'departamento_id' => 22],
            ['nombre' => "LINARES", 'departamento_id' => 22],
            ['nombre' => "LOS ANDES", 'departamento_id' => 22],
            ['nombre' => "MAGUI", 'departamento_id' => 22],
            ['nombre' => "MALLAMA", 'departamento_id' => 22],
            ['nombre' => "MOSQUERA", 'departamento_id' => 22],
            ['nombre' => "NARIÑO", 'departamento_id' => 22],
            ['nombre' => "OLAYA HERRERA", 'departamento_id' => 22],
            ['nombre' => "OSPINA", 'departamento_id' => 22],
            ['nombre' => "PASTO", 'departamento_id' => 22],
            ['nombre' => "POLICARPA", 'departamento_id' => 22],
            ['nombre' => "POTOSI", 'departamento_id' => 22],
            ['nombre' => "PROVIDENCIA", 'departamento_id' => 22],
            ['nombre' => "PUERRES", 'departamento_id' => 22],
            ['nombre' => "PUPIALES", 'departamento_id' => 22],
            ['nombre' => "RICAURTE", 'departamento_id' => 22],
            ['nombre' => "ROBERTO PAYAN", 'departamento_id' => 22],
            ['nombre' => "SAMANIEGO", 'departamento_id' => 22],
            ['nombre' => "SAN BERNARDO", 'departamento_id' => 22],
            ['nombre' => "SAN LORENZO", 'departamento_id' => 22],
            ['nombre' => "SAN PABLO", 'departamento_id' => 22],
            ['nombre' => "SAN PEDRO DE CARTAGO", 'departamento_id' => 22],
            ['nombre' => "SANDONA", 'departamento_id' => 22],
            ['nombre' => "SANTA BARBARA", 'departamento_id' => 22],
            ['nombre' => "SANTACRUZ", 'departamento_id' => 22],
            ['nombre' => "SAPUYES", 'departamento_id' => 22],
            ['nombre' => "TAMINANGO", 'departamento_id' => 22],
            ['nombre' => "TANGUA", 'departamento_id' => 22],
            ['nombre' => "TUMACO", 'departamento_id' => 22],
            ['nombre' => "TUQUERRES", 'departamento_id' => 22],
            ['nombre' => "YACUANQUER", 'departamento_id' => 22],
            ['nombre' => "ABREGO", 'departamento_id' => 23],
            ['nombre' => "ARBOLEDAS", 'departamento_id' => 23],
            ['nombre' => "BOCHALEMA", 'departamento_id' => 23],
            ['nombre' => "BUCARASICA", 'departamento_id' => 23],
            ['nombre' => "CÁCHIRA", 'departamento_id' => 23],
            ['nombre' => "CÁCOTA", 'departamento_id' => 23],
            ['nombre' => "CHINÁCOTA", 'departamento_id' => 23],
            ['nombre' => "CHITAGÁ", 'departamento_id' => 23],
            ['nombre' => "CONVENCIÓN", 'departamento_id' => 23],
            ['nombre' => "CÚCUTA", 'departamento_id' => 23],
            ['nombre' => "CUCUTILLA", 'departamento_id' => 23],
            ['nombre' => "DURANIA", 'departamento_id' => 23],
            ['nombre' => "EL CARMEN", 'departamento_id' => 23],
            ['nombre' => "EL TARRA", 'departamento_id' => 23],
            ['nombre' => "EL ZULIA", 'departamento_id' => 23],
            ['nombre' => "GRAMALOTE", 'departamento_id' => 23],
            ['nombre' => "HACARI", 'departamento_id' => 23],
            ['nombre' => "HERRÁN", 'departamento_id' => 23],
            ['nombre' => "LA ESPERANZA", 'departamento_id' => 23],
            ['nombre' => "LA PLAYA", 'departamento_id' => 23],
            ['nombre' => "LABATECA", 'departamento_id' => 23],
            ['nombre' => "LOS PATIOS", 'departamento_id' => 23],
            ['nombre' => "LOURDES", 'departamento_id' => 23],
            ['nombre' => "MUTISCUA", 'departamento_id' => 23],
            ['nombre' => "OCAÑA", 'departamento_id' => 23],
            ['nombre' => "PAMPLONA", 'departamento_id' => 23],
            ['nombre' => "PAMPLONITA", 'departamento_id' => 23],
            ['nombre' => "PUERTO SANTANDER", 'departamento_id' => 23],
            ['nombre' => "RAGONVALIA", 'departamento_id' => 23],
            ['nombre' => "SALAZAR", 'departamento_id' => 23],
            ['nombre' => "SAN CALIXTO", 'departamento_id' => 23],
            ['nombre' => "SAN CAYETANO", 'departamento_id' => 23],
            ['nombre' => "SANTIAGO", 'departamento_id' => 23],
            ['nombre' => "SARDINATA", 'departamento_id' => 23],
            ['nombre' => "SILOS", 'departamento_id' => 23],
            ['nombre' => "TEORAMA", 'departamento_id' => 23],
            ['nombre' => "TIBÚ", 'departamento_id' => 23],
            ['nombre' => "TOLEDO", 'departamento_id' => 23],
            ['nombre' => "VILLA CARO", 'departamento_id' => 23],
            ['nombre' => "VILLA DEL ROSARIO", 'departamento_id' => 23],
            ['nombre' => "COLÓN", 'departamento_id' => 24],
            ['nombre' => "MOCOA", 'departamento_id' => 24],
            ['nombre' => "ORITO", 'departamento_id' => 24],
            ['nombre' => "PUERTO ASÍS", 'departamento_id' => 24],
            ['nombre' => "PUERTO CAICEDO", 'departamento_id' => 24],
            ['nombre' => "PUERTO GUZMÁN", 'departamento_id' => 24],
            ['nombre' => "PUERTO LEGUÍZAMO", 'departamento_id' => 24],
            ['nombre' => "SAN FRANCISCO", 'departamento_id' => 24],
            ['nombre' => "SAN MIGUEL", 'departamento_id' => 24],
            ['nombre' => "SANTIAGO", 'departamento_id' => 24],
            ['nombre' => "SIBUNDOY", 'departamento_id' => 24],
            ['nombre' => "VALLE DEL GUAMUEZ", 'departamento_id' => 24],
            ['nombre' => "VILLAGARZÓN", 'departamento_id' => 24],
            ['nombre' => "ARMENIA", 'departamento_id' => 25],
            ['nombre' => "BUENAVISTA", 'departamento_id' => 25],
            ['nombre' => "CALARCÁ", 'departamento_id' => 25],
            ['nombre' => "CIRCASIA", 'departamento_id' => 25],
            ['nombre' => "CÓRDOBA", 'departamento_id' => 25],
            ['nombre' => "FILANDIA", 'departamento_id' => 25],
            ['nombre' => "GÉNOVA", 'departamento_id' => 25],
            ['nombre' => "LA TEBAIDA", 'departamento_id' => 25],
            ['nombre' => "MONTENEGRO", 'departamento_id' => 25],
            ['nombre' => "PIJAO", 'departamento_id' => 25],
            ['nombre' => "QUIMBAYA", 'departamento_id' => 25],
            ['nombre' => "SALENTO", 'departamento_id' => 25],
            ['nombre' => "APIA", 'departamento_id' => 26],
            ['nombre' => "BALBOA", 'departamento_id' => 26],
            ['nombre' => "BELÉN DE UMBRÍA", 'departamento_id' => 26],
            ['nombre' => "DOSQUEBRADAS", 'departamento_id' => 26],
            ['nombre' => "GUATICA", 'departamento_id' => 26],
            ['nombre' => "LA CELIA", 'departamento_id' => 26],
            ['nombre' => "LA VIRGINIA", 'departamento_id' => 26],
            ['nombre' => "MARSELLA", 'departamento_id' => 26],
            ['nombre' => "MISTRATO", 'departamento_id' => 26],
            ['nombre' => "PEREIRA", 'departamento_id' => 26],
            ['nombre' => "PUEBLO RICO", 'departamento_id' => 26],
            ['nombre' => "QUINCHÍA", 'departamento_id' => 26],
            ['nombre' => "SANTA ROSA DE CABAL", 'departamento_id' => 26],
            ['nombre' => "SANTUARIO", 'departamento_id' => 26],
            ['nombre' => "PROVIDENCIA", 'departamento_id' => 27],
            ['nombre' => "SAN ANDRES", 'departamento_id' => 27],
            ['nombre' => "AGUADA", 'departamento_id' => 28],
            ['nombre' => "ALBANIA", 'departamento_id' => 28],
            ['nombre' => "ARATOCA", 'departamento_id' => 28],
            ['nombre' => "BARBOSA", 'departamento_id' => 28],
            ['nombre' => "BARICHARA", 'departamento_id' => 28],
            ['nombre' => "BARRANCABERMEJA", 'departamento_id' => 28],
            ['nombre' => "BETULIA", 'departamento_id' => 28],
            ['nombre' => "BOLÍVAR", 'departamento_id' => 28],
            ['nombre' => "BUCARAMANGA", 'departamento_id' => 28],
            ['nombre' => "CABRERA", 'departamento_id' => 28],
            ['nombre' => "CALIFORNIA", 'departamento_id' => 28],
            ['nombre' => "CAPITANEJO", 'departamento_id' => 28],
            ['nombre' => "CARCASI", 'departamento_id' => 28],
            ['nombre' => "CEPITA", 'departamento_id' => 28],
            ['nombre' => "CERRITO", 'departamento_id' => 28],
            ['nombre' => "CHARALÁ", 'departamento_id' => 28],
            ['nombre' => "CHARTA", 'departamento_id' => 28],
            ['nombre' => "CHIMA", 'departamento_id' => 28],
            ['nombre' => "CHIPATÁ", 'departamento_id' => 28],
            ['nombre' => "CIMITARRA", 'departamento_id' => 28],
            ['nombre' => "CONCEPCIÓN", 'departamento_id' => 28],
            ['nombre' => "CONFINES", 'departamento_id' => 28],
            ['nombre' => "CONTRATACIÓN", 'departamento_id' => 28],
            ['nombre' => "COROMORO", 'departamento_id' => 28],
            ['nombre' => "CURITÍ", 'departamento_id' => 28],
            ['nombre' => "EL CARMEN DE CHUCURÍ", 'departamento_id' => 28],
            ['nombre' => "EL GUACAMAYO", 'departamento_id' => 28],
            ['nombre' => "EL PEÑÓN", 'departamento_id' => 28],
            ['nombre' => "EL PLAYÓN", 'departamento_id' => 28],
            ['nombre' => "ENCINO", 'departamento_id' => 28],
            ['nombre' => "ENCISO", 'departamento_id' => 28],
            ['nombre' => "FLORIÁN", 'departamento_id' => 28],
            ['nombre' => "FLORIDABLANCA", 'departamento_id' => 28],
            ['nombre' => "GALÁN", 'departamento_id' => 28],
            ['nombre' => "GAMBITA", 'departamento_id' => 28],
            ['nombre' => "GIRÓN", 'departamento_id' => 28],
            ['nombre' => "GUACA", 'departamento_id' => 28],
            ['nombre' => "GUADALUPE", 'departamento_id' => 28],
            ['nombre' => "GUAPOTA", 'departamento_id' => 28],
            ['nombre' => "GUAVATÁ", 'departamento_id' => 28],
            ['nombre' => "GUEPSA", 'departamento_id' => 28],
            ['nombre' => "HATO", 'departamento_id' => 28],
            ['nombre' => "JESÚS MARIA", 'departamento_id' => 28],
            ['nombre' => "JORDÁN", 'departamento_id' => 28],
            ['nombre' => "LA BELLEZA", 'departamento_id' => 28],
            ['nombre' => "LA PAZ", 'departamento_id' => 28],
            ['nombre' => "LANDAZURI", 'departamento_id' => 28],
            ['nombre' => "LEBRIJA", 'departamento_id' => 28],
            ['nombre' => "LOS SANTOS", 'departamento_id' => 28],
            ['nombre' => "MACARAVITA", 'departamento_id' => 28],
            ['nombre' => "MÁLAGA", 'departamento_id' => 28],
            ['nombre' => "MATANZA", 'departamento_id' => 28],
            ['nombre' => "MOGOTES", 'departamento_id' => 28],
            ['nombre' => "MOLAGAVITA", 'departamento_id' => 28],
            ['nombre' => "OCAMONTE", 'departamento_id' => 28],
            ['nombre' => "OIBA", 'departamento_id' => 28],
            ['nombre' => "ONZAGA", 'departamento_id' => 28],
            ['nombre' => "PALMAR", 'departamento_id' => 28],
            ['nombre' => "PALMAS DEL SOCORRO", 'departamento_id' => 28],
            ['nombre' => "PÁRAMO", 'departamento_id' => 28],
            ['nombre' => "PIEDECUESTA", 'departamento_id' => 28],
            ['nombre' => "PINCHOTE", 'departamento_id' => 28],
            ['nombre' => "PUENTE NACIONAL", 'departamento_id' => 28],
            ['nombre' => "PUERTO PARRA", 'departamento_id' => 28],
            ['nombre' => "PUERTO WILCHES", 'departamento_id' => 28],
            ['nombre' => "RIONEGRO", 'departamento_id' => 28],
            ['nombre' => "SABANA DE TORRES", 'departamento_id' => 28],
            ['nombre' => "SAN ANDRÉS", 'departamento_id' => 28],
            ['nombre' => "SAN BENITO", 'departamento_id' => 28],
            ['nombre' => "SAN GIL", 'departamento_id' => 28],
            ['nombre' => "SAN JOAQUÍN", 'departamento_id' => 28],
            ['nombre' => "SAN JOSÉ DE MIRANDA", 'departamento_id' => 28],
            ['nombre' => "SAN MIGUEL", 'departamento_id' => 28],
            ['nombre' => "SAN VICENTE DE CHUCURÍ", 'departamento_id' => 28],
            ['nombre' => "SANTA BÁRBARA", 'departamento_id' => 28],
            ['nombre' => "SANTA HELENA DEL OPÓN", 'departamento_id' => 28],
            ['nombre' => "SIMACOTA", 'departamento_id' => 28],
            ['nombre' => "SOCORRO", 'departamento_id' => 28],
            ['nombre' => "SUAITA", 'departamento_id' => 28],
            ['nombre' => "SUCRE", 'departamento_id' => 28],
            ['nombre' => "SURATA", 'departamento_id' => 28],
            ['nombre' => "TONA", 'departamento_id' => 28],
            ['nombre' => "VALLE DE SAN JOSÉ", 'departamento_id' => 28],
            ['nombre' => "VÉLEZ", 'departamento_id' => 28],
            ['nombre' => "VETAS", 'departamento_id' => 28],
            ['nombre' => "VILLANUEVA", 'departamento_id' => 28],
            ['nombre' => "ZAPATOCA", 'departamento_id' => 28],
            ['nombre' => "BUENAVISTA", 'departamento_id' => 29],
            ['nombre' => "CAIMITO", 'departamento_id' => 29],
            ['nombre' => "CHALÁN", 'departamento_id' => 29],
            ['nombre' => "COLOSO", 'departamento_id' => 29],
            ['nombre' => "COROZAL", 'departamento_id' => 29],
            ['nombre' => "COVEÑAS", 'departamento_id' => 29],
            ['nombre' => "EL ROBLE", 'departamento_id' => 29],
            ['nombre' => "GALERAS", 'departamento_id' => 29],
            ['nombre' => "GUARANDA", 'departamento_id' => 29],
            ['nombre' => "LA UNIÓN", 'departamento_id' => 29],
            ['nombre' => "LOS PALMITOS", 'departamento_id' => 29],
            ['nombre' => "MAJAGUAL", 'departamento_id' => 29],
            ['nombre' => "MORROA", 'departamento_id' => 29],
            ['nombre' => "OVEJAS", 'departamento_id' => 29],
            ['nombre' => "PALMITO", 'departamento_id' => 29],
            ['nombre' => "SAMPUES", 'departamento_id' => 29],
            ['nombre' => "SAN BENITO ABAD", 'departamento_id' => 29],
            ['nombre' => "SAN JUAN DE BETULIA", 'departamento_id' => 29],
            ['nombre' => "SAN MARCOS", 'departamento_id' => 29],
            ['nombre' => "SAN ONOFRE", 'departamento_id' => 29],
            ['nombre' => "SAN PEDRO", 'departamento_id' => 29],
            ['nombre' => "SANTIAGO DE TOLÚ", 'departamento_id' => 29],
            ['nombre' => "SINCÉ", 'departamento_id' => 29],
            ['nombre' => "SINCELEJO", 'departamento_id' => 29],
            ['nombre' => "SUCRE", 'departamento_id' => 29],
            ['nombre' => "TOLUVIEJO", 'departamento_id' => 29],
            ['nombre' => "ALPUJARRA", 'departamento_id' => 30],
            ['nombre' => "ALVARADO", 'departamento_id' => 30],
            ['nombre' => "AMBALEMA", 'departamento_id' => 30],
            ['nombre' => "ANZOATEGUI", 'departamento_id' => 30],
            ['nombre' => "ARMERO", 'departamento_id' => 30],
            ['nombre' => "ATACO", 'departamento_id' => 30],
            ['nombre' => "CAJAMARCA", 'departamento_id' => 30],
            ['nombre' => "CARMEN DE APICALÁ", 'departamento_id' => 30],
            ['nombre' => "CASABIANCA", 'departamento_id' => 30],
            ['nombre' => "CHAPARRAL", 'departamento_id' => 30],
            ['nombre' => "COELLO", 'departamento_id' => 30],
            ['nombre' => "COYAIMA", 'departamento_id' => 30],
            ['nombre' => "CUNDAY", 'departamento_id' => 30],
            ['nombre' => "DOLORES", 'departamento_id' => 30],
            ['nombre' => "ESPINAL", 'departamento_id' => 30],
            ['nombre' => "FALÁN", 'departamento_id' => 30],
            ['nombre' => "FLANDES", 'departamento_id' => 30],
            ['nombre' => "FRESNO", 'departamento_id' => 30],
            ['nombre' => "GUAMO", 'departamento_id' => 30],
            ['nombre' => "HERVEO", 'departamento_id' => 30],
            ['nombre' => "HONDA", 'departamento_id' => 30],
            ['nombre' => "IBAGUÉ", 'departamento_id' => 30],
            ['nombre' => "ICONONZO", 'departamento_id' => 30],
            ['nombre' => "LÉRIDA", 'departamento_id' => 30],
            ['nombre' => "LÍBANO", 'departamento_id' => 30],
            ['nombre' => "MARIQUITA", 'departamento_id' => 30],
            ['nombre' => "MELGAR", 'departamento_id' => 30],
            ['nombre' => "MURILLO", 'departamento_id' => 30],
            ['nombre' => "NATAGAIMA", 'departamento_id' => 30],
            ['nombre' => "ORTEGA", 'departamento_id' => 30],
            ['nombre' => "PALOCABILDO", 'departamento_id' => 30],
            ['nombre' => "PIEDRAS", 'departamento_id' => 30],
            ['nombre' => "PLANADAS", 'departamento_id' => 30],
            ['nombre' => "PRADO", 'departamento_id' => 30],
            ['nombre' => "PURIFICACIÓN", 'departamento_id' => 30],
            ['nombre' => "RIOBLANCO", 'departamento_id' => 30],
            ['nombre' => "RONCESVALLES", 'departamento_id' => 30],
            ['nombre' => "ROVIRA", 'departamento_id' => 30],
            ['nombre' => "SALDAÑA", 'departamento_id' => 30],
            ['nombre' => "SAN ANTONIO", 'departamento_id' => 30],
            ['nombre' => "SAN LUIS", 'departamento_id' => 30],
            ['nombre' => "SANTA ISABEL", 'departamento_id' => 30],
            ['nombre' => "SUÁREZ", 'departamento_id' => 30],
            ['nombre' => "VALLE DE SAN JUAN", 'departamento_id' => 30],
            ['nombre' => "VENADILLO", 'departamento_id' => 30],
            ['nombre' => "VILLAHERMOSA", 'departamento_id' => 30],
            ['nombre' => "VILLARRICA", 'departamento_id' => 30],
            ['nombre' => "ALCALÁ", 'departamento_id' => 31],
            ['nombre' => "ANDALUCÍA", 'departamento_id' => 31],
            ['nombre' => "ANSERMANUEVO", 'departamento_id' => 31],
            ['nombre' => "ARGELIA", 'departamento_id' => 31],
            ['nombre' => "BOLÍVAR", 'departamento_id' => 31],
            ['nombre' => "BUENAVENTURA", 'departamento_id' => 31],
            ['nombre' => "BUGA", 'departamento_id' => 31],
            ['nombre' => "BUGALAGRANDE", 'departamento_id' => 31],
            ['nombre' => "CAICEDONIA", 'departamento_id' => 31],
            ['nombre' => "CALI", 'departamento_id' => 31],
            ['nombre' => "CALIMA - EL DARIÉN", 'departamento_id' => 31],
            ['nombre' => "CANDELARIA", 'departamento_id' => 31],
            ['nombre' => "CARTAGO", 'departamento_id' => 31],
            ['nombre' => "DAGUA", 'departamento_id' => 31],
            ['nombre' => "EL AGUILA", 'departamento_id' => 31],
            ['nombre' => "EL CAIRO", 'departamento_id' => 31],
            ['nombre' => "EL CERRITO", 'departamento_id' => 31],
            ['nombre' => "EL DOVIO", 'departamento_id' => 31],
            ['nombre' => "FLORIDA", 'departamento_id' => 31],
            ['nombre' => "GINEBRA", 'departamento_id' => 31],
            ['nombre' => "GUACARÍ", 'departamento_id' => 31],
            ['nombre' => "JAMUNDÍ", 'departamento_id' => 31],
            ['nombre' => "LA CUMBRE", 'departamento_id' => 31],
            ['nombre' => "LA UNIÓN", 'departamento_id' => 31],
            ['nombre' => "LA VICTORIA", 'departamento_id' => 31],
            ['nombre' => "OBANDO", 'departamento_id' => 31],
            ['nombre' => "PALMIRA", 'departamento_id' => 31],
            ['nombre' => "PRADERA", 'departamento_id' => 31],
            ['nombre' => "RESTREPO", 'departamento_id' => 31],
            ['nombre' => "RIOFRÍO", 'departamento_id' => 31],
            ['nombre' => "ROLDANILLO", 'departamento_id' => 31],
            ['nombre' => "SAN PEDRO", 'departamento_id' => 31],
            ['nombre' => "SEVILLA", 'departamento_id' => 31],
            ['nombre' => "TORO", 'departamento_id' => 31],
            ['nombre' => "TRUJILLO", 'departamento_id' => 31],
            ['nombre' => "TULÚA", 'departamento_id' => 31],
            ['nombre' => "ULLOA", 'departamento_id' => 31],
            ['nombre' => "VERSALLES", 'departamento_id' => 31],
            ['nombre' => "VIJES", 'departamento_id' => 31],
            ['nombre' => "YOTOCO", 'departamento_id' => 31],
            ['nombre' => "YUMBO", 'departamento_id' => 31],
            ['nombre' => "ZARZAL", 'departamento_id' => 31],
            ['nombre' => "CARURÚ", 'departamento_id' => 32],
            ['nombre' => "MITÚ", 'departamento_id' => 32],
            ['nombre' => "PACOA", 'departamento_id' => 32],
            ['nombre' => "PAPUNAUA", 'departamento_id' => 32],
            ['nombre' => "TARAIRA", 'departamento_id' => 32],
            ['nombre' => "YAVARATÉ", 'departamento_id' => 32],
            ['nombre' => "CUMARIBO", 'departamento_id' => 33],
            ['nombre' => "LA PRIMAVERA", 'departamento_id' => 33],
            ['nombre' => "PUERTO CARREÑO", 'departamento_id' => 33],
            ['nombre' => "SANTA ROSALIA", 'departamento_id' => 33]
        );

        foreach ($data as $dato) {
            Ciudad::create($dato);
        }
    }
}
